#279: Ensure no commits with emails other than *.github.com (#280)

diff --git a/.github/workflows/twe.yml b/.github/workflows/twe.yml
--- a/.github/workflows/twe.yml
+++ b/.github/workflows/twe.yml
@@ -19,7 +19,33 @@ env:
   TWE_RESOURCES_PATH: src/main/resources/twe
 
 jobs:
+
+  check-commit-emails:
+    runs-on: ubuntu-latest
+    steps:
+
+      - name: Checkout TWE
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
+        with:
+          path: ${{ env.TWE_PATH }}
+
+      - name: Check commit emails
+        working-directory: ${{ env.TWE_PATH }}
+        run: |
+          git fetch origin ${{ github.base_ref }}
+          echo ${{ github.base_ref }}
+          git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%ae%n%ce" | sort -u > emails.txt
+          echo "Found email(s):"
+          cat emails.txt
+          if grep -Evi '(^noreply@github\.com$|@users\.noreply\.github\.com$)' emails.txt | grep -v '^\s*$' > invalid.txt; then
+            echo "Invalid email(s):"
+            cat invalid.txt
+            exit 1
+          fi
+
   build:
+
+    needs: check-commit-emails
 
     runs-on: ubuntu-latest
 
@@ -36,7 +62,7 @@ jobs:
     - name: Checkout TWE
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
       with:
-        path: tax_withholding_estimator
+        path: ${{ env.TWE_PATH }}
 
     - name: Setup Java
       uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
